steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/buoyant-ceiling-402604/advertising_roi_model', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/buoyant-ceiling-402604/advertising_roi']

- name: 'gcr.io/buoyant-ceiling-402604/advertising_roi'
  entrypoint: 'bash'
  args:
   - '-c'
   - |
      python -m pytest

- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/sidoncloud/your-repository-name.git']

- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'model-training-repo/advertising_model_training.py', 'gs://us-central1-mlops-airflow-faa6f9bc-bucket/dags']

images:
- 'gcr.io/buoyant-ceiling-402604/advertising_roi'

options:
  logging: CLOUD_LOGGING_ONLY